os: linux
language: java
jdk:
    - openjdk8
env:
    - NODE_VERSION="12"
before_install:
    - nvm install $NODE_VERSION
    - node --version
    - npm --version
jobs:
    include:
        - stage: build
          name: "Build"
          script: ./build-config/travis-build.sh
        - stage: deploy
          name: "Deploy"
          script: ./build-config/travis-deploy.sh
