os: linux
language: java
jdk:
  - openjdk8
before_install:
  - nvm install 12
  - node --version
  - npm --version
script:
  - ./build-config/travis-build-java.sh
  - ./build-config/travis-build-node.sh
deploy:
  - provider: script
    script: ./build-config/travis-deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./build-config/travis-deploy.sh
    skip_cleanup: true
    on:
      tags: true
